services:
  valheim:
    container_name: valheim
    image: ghcr.io/lloesche/valheim-server
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    # network_mode: "host"
    cap_add:
      - sys_nice
    restart: always
    stop_grace_period: 2m
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file: "valheim.env"
