services:
  torrent:
    container_name: torrent

    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - coloc-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - ./torrent/qbittorrent:/config
      - ./torrent/data/torrents:/data/torrents
      - type: bind
        source: ./downloads
        target: /downloads
    # depends_on:
    #   gluetun:
    #     condition: service_healthy
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: ./downloads
        target: /downloads
    environment:
      - JELLYFIN_PublishedServerUrl=https://stream.coloc.me
    # ports:
    #   - 8096:8096/tcp
    networks:
      - coloc-net

networks:
  coloc-net:
    name: coloc-net
    external: true
