services:
  vintagestory:
    image: zsuatem/vintagestory:1.20.3
    container_name: vintagestory
    restart: always
    ports:
      - 42420:42420/tcp
    volumes:
      - ./server/data:/vintagestory/data
    stdin_open: true
    tty: true
